platform :ios, "7.0"

xcodeproj "DFImageManagerSample.xcodeproj"

source "https://github.com/CocoaPods/Specs.git"

pod "DFImageManager", :path => "../"
pod "DFImageManager/AFNetworking", :path => "../"
pod "DFImageManager/GIF", :path => "../"

pod "AFNetworking/UIKit", "~> 2.0"
