platform :ios, "8.0"

project "DFImageManager.xcodeproj"

source "https://github.com/CocoaPods/Specs.git"

target 'DFImageManager-Example' do
	pod "DFImageManager", :path => "../"
	pod "DFImageManager/AFNetworking", :path => "../"
	pod "DFImageManager/GIF", :path => "../"
	pod "DFImageManager/WebP", :path => "../"
	pod "DFImageManager/PhotosKit", :path => "../"

	pod "AFNetworking/UIKit", "~> 3.0"
end

target 'DFImageManager-Tests' do
	pod "DFImageManager", :path => "../"
	pod "DFImageManager/AFNetworking", :path => "../"
	pod "DFImageManager/GIF", :path => "../"
	pod "DFImageManager/WebP", :path => "../"
	
	pod "OHHTTPStubs"
end
