// Playground - noun: a place where people can play

import UIKit
import DFImageManagerKit
import XCPlayground

// WARNING: DFImageManager Swift interfaces are automatically generated by Xcode.

let manager = DFImageManager.sharedManager()

let imageURL = NSURL(string: "https://raw.githubusercontent.com/kean/DFImageManager/master/DFImageManager/Tests/Resources/Image.jpg")

// Request fullsize image
manager.requestImageForResource(imageURL) { (image: UIImage!, [NSObject : AnyObject]!) -> Void in
    var fetchedImage = image
}

// Request scaled image
manager.requestImageForResource(imageURL, targetSize: CGSize(width: 100, height: 100), contentMode: DFImageContentMode.AspectFill, options: nil) { (image: UIImage!, [NSObject : AnyObject]!) -> Void in
    var fetchedImage = image
}

XCPSetExecutionShouldContinueIndefinitely()
